# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3de46bd1653a8cc281216f9ad439ec9ba89378e044079b7c25cfc975664d1a4b7bc02a2b6b806ecf273a4ccce6f4cef70df67f6eeae750b1cad6da5906a8f30

test:
  secret_key_base: 3b34da81abb54ed09317b7d7632c737cbea0bcba5df79bc78a009b8ae409ad9fa30bb7ace74ba90e4ab4664911a10ae10e6878b6f92f8b743f3c2826184e992a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
